PollApplication/Models/Poll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollApplication.Models
{
    public class Poll
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public ICollection<Question> Questions { get; set; }
        public int Count { get; set; }
        public PollType Type { get; set; }

        public Poll()
        {
        }
    }
}

PollApplication/Models/PollViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollApplication.Models
{
    public class PollViewModel
    {
        public string SearchString { get; set; }
        public List<Poll> Polls { get; set; }
    }
}

PollApplication/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace PollApplication.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public List<Variant> Variants { get; set; }
        public int? LinkedPollId { get; set; }
        [ForeignKey("LinkedPollId")]
        public Poll LinkedPoll { get; set; }
        public int QuestionIndex { get; set; }

        public Question()
        {
            Variants = new List<Variant>();
        }
    }
}

PollApplication/Controllers/PollCreationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.EntityFrameworkCore;
using PollApplication.Models;
using PollApplication.Repository;

namespace PollApplication.Controllers
{
    public class PollCreationController : Controller
    {

        private UnitOfWork unitOfWork;
        public PollCreationController(ApplicationContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Poll()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Questions(int count, string name, PollType type, bool isIncorrect)
        {
            ViewBag.Count = count;
            ViewBag.Name = name;
            ViewBag.Type = type;
            ViewBag.IsIncorrect = isIncorrect;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Poll(PollModel model)
        {
            if (ModelState.IsValid)
            {
                Poll poll = unitOfWork.Polls.GetBookList().FirstOrDefault(p => p.Name == model.Name);
                if (poll == null)
                {
                    return RedirectToAction($"Questions", new {model.Count, model.Name, model.Type});
                }

                ModelState.AddModelError("", "Некорректные данные.");
            }

            ModelState.AddModelError("", "Некорректные данные.");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Questions(List<QuestionModel> model)
        {
            if (ModelState.IsValid)
            {
                int questionIndex = 1;
                Poll pollToAdd = new Poll() {Name = model.First().Name, Date = DateTime.Now, Type = model.First().Type, Count = model.First().Count};
                unitOfWork.Polls.Create(pollToAdd);
                foreach (var q in model)
                {
                    var questionToAdd = new Question()
                        {LinkedPoll = pollToAdd, QuestionIndex = questionIndex, QuestionText = q.Text};
                    unitOfWork.Questions.Create(questionToAdd);
                    unitOfWork.Save();
                    int variantIndex = 1;
                    foreach (var variant in q.Variants)
                    {
                        unitOfWork.Variants.Create(new Variant() {Question = questionToAdd, Text = variant, VariantIndex = variantIndex++});
                    }

                    unitOfWork.Save();
                    questionIndex++;
                }

                return RedirectToAction("Index", "Home");
            }

            return Questions(model.Count, model.First().Name, model.First().Type, true);
        }
    }
}

PollApplication/Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PollApplication.Models;

namespace PollApplication.Controllers
{
    public class PollsController : Controller
    {
        private ApplicationContext _context;
        private int userId;
        public PollsController(ApplicationContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var email = httpContextAccessor.HttpContext.User.Claims.First(claim => claim.Value.Contains("@")).Value;
            userId = _context.Users.FirstOrDefault((user =>
                user.Email == email)).Id;
        }

        public async Task<IActionResult> Index(string searchString, int user)
        {
            userId = user;
            var polls = from p in _context.Polls
                select p;
            polls = polls.OrderByDescending((poll => poll.Date));

            if (!string.IsNullOrEmpty(searchString))
            {
                polls = polls.Where((poll => poll.Name.Contains(searchString)));
            }

            PollViewModel pvm = new PollViewModel()
            {
                Polls = await polls.ToListAsync(),
            };

            return View(pvm);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(string searchString)
        {
            var polls = from p in _context.Polls select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                polls = polls.Where((poll => poll.Name.Contains(searchString)));
            }

            PollViewModel pvm = new PollViewModel()
            {
                Polls = await polls.ToListAsync(),
            };

            return View(pvm);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteById(int id)
        {
            foreach (var q in _context.Questions.Where((question => question.LinkedPollId==id)))
            {
                foreach (var answer in _context.Answers.Where((answer => answer.QuestionId==q.Id)))
                {
                    _context.Answers.Remove(answer);
                }

                foreach (var variant in _context.Variants.Where((varia => varia.QuestionId==q.Id)))
                {
                    _context.Variants.Remove(variant);
                }

                _context.Questions.Remove(q);
            }

            _context.Polls.RemoveRange(await _context.Polls.FirstOrDefaultAsync((poll => poll.Id==id)));
            await _context.SaveChangesAsync();

            return RedirectToAction("Delete");
        }

        public async Task<IActionResult> Pass(int id, bool redirect = false)
        {
            Poll p = await _context.Polls.FirstOrDefaultAsync(poll => poll.Id == id);
            if (p is null)
            {
                return RedirectToAction("Index");
            }

            List<Question> questions = _context.Questions.Where((question => question.LinkedPollId == p.Id)).ToList();
            if (!redirect)
            {
                foreach (var q in questions)
                {
                    var foundAnswer = await _context.Answers.FirstOrDefaultAsync((a =>
                        a.UserId == userId && a.QuestionId == q.Id));
                    if (foundAnswer != null)
                    {
                        ViewBag.UserId = userId;
                        ViewBag.PollId = id;
                        return View("Modal");
                    }
                }
            }

            ViewBag.PollName = p.Name;
            if (p.Type == PollType.Check)
            {
                return PassCheck(questions);
            }

            return PassRadio(questions);
        }

        public async Task<IActionResult> Stat(int id)
        {
            Poll p = await _context.Polls.FirstOrDefaultAsync(poll => poll.Id == id);
            if (p is null)
            {
                return RedirectToAction("Index");
            }

            List<Question> questions = await _context.Questions.Where((question => question.LinkedPollId == p.Id)).ToListAsync();
            List<StatViewModel> statView = new List<StatViewModel>();
            int counter = 1;
            foreach (var q in questions)
            {
                List<SimpleReportViewModel> answers = new List<SimpleReportViewModel>();
                foreach (var variant in _context.Variants.Where((variant => variant.QuestionId==q.Id)))
                {
                    SimpleReportViewModel report = new SimpleReportViewModel()
                    {
                        DimensionOne = variant.Text,
                        Quantity = await _context.Answers.Where((answer => answer.VariantId==variant.Id)).CountAsync()
                    };

                    answers.Add(report);
                }

                statView.Add(new StatViewModel(){Models = answers, QuestionText = "Вопрос "+counter+". "+q.QuestionText, Id = counter});
                counter++;
            }

            return View(statView);
        }

        public IActionResult PassRadio(List<Question> questions)
        {
            List<QuestionRadioViewModel> viewList = new List<QuestionRadioViewModel>();
            foreach (Question q in questions)
            {
                QuestionRadioViewModel model = new QuestionRadioViewModel()
                {
                    QuestionId = q.Id,
                    Question = q.QuestionText,
                    Variants = _context.Variants.Where((variant => variant.QuestionId == q.Id))
                        .ToList(),
                };
                viewList.Add(model);
            }


            return View("PassRadio", viewList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PassRadio(List<QuestionRadioViewModel> models)
        {
            if (userId == 1)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                foreach (var model in models)
                {
                    if (model.AnswerId == 0)
                    {
                        ModelState.AddModelError("", "Некорректные ответы");
                        return View(models);
                    }

                    var foundAnswer = await _context.Answers.FirstOrDefaultAsync((a =>
                        a.UserId == userId && a.QuestionId == model.QuestionId));
                    if (foundAnswer != null)
                    {
                        _context.Answers.Remove(foundAnswer);
                    }

                    PollAnswer answer = new PollAnswer()
                    {
                        UserId = userId, QuestionId = model.QuestionId, VariantId = model.AnswerId
                    };

                    _context.Answers.Add(answer);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Некорректные ответы");
            return View(models);
        }

        public IActionResult PassCheck(List<Question> questions)
        {
            List<QuestionCheckViewModel> viewList = new List<QuestionCheckViewModel>();
            foreach (Question q in questions)
            {
                QuestionCheckViewModel model = new QuestionCheckViewModel()
                {
                    QuestionId = q.Id,
                    Question = q.QuestionText,
                    Variants = _context.Variants.Where((variant => variant.QuestionId == q.Id))
                        .ToList(),
                };
                viewList.Add(model);
            }

            return View("PassCheck", viewList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PassCheck(List<QuestionCheckViewModel> models)
        {
            if (userId == 1)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                foreach (var model in models)
                {
                    if (model.Answers.Count==0)
                    {
                        ModelState.AddModelError("", "Некорректные ответы");
                        return View(models);
                    }

                    var foundAnswers = _context.Answers.Where((a =>
                        a.UserId == userId && a.QuestionId == model.QuestionId));
                    if (foundAnswers.Count() != 0)
                    {
                        foreach (var answerFound in foundAnswers)
                        {
                            _context.Answers.Remove(answerFound);
                        }
                    }

                    for (int i = 0; i < model.Answers.Count; i++)
                    {
                        PollAnswer answer = new PollAnswer()
                        {
                            UserId = userId,
                            QuestionId = model.QuestionId,
                            VariantId = model.Variants[model.Answers[i]].Id
                        };

                        _context.Answers.Add(answer);
                        await _context.SaveChangesAsync();
                    }
                }

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Некорректные ответы");
            return View(models);
        }
    }
}

PollApplication/Views/PollCreation/Poll.cshtml
@model PollApplication.Models.PollModel

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<h1>Опрос</h1>
<form asp-action="Poll" asp-controller="PollCreation">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div class="form-group">
            <label asp-for="Name">Введите название опроса</label>
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name" />
        </div>
        <div class="form-group">
            <label asp-for="Type">Выберите тип опроса</label>
            <select asp-for="Type" asp-items="@Html.GetEnumSelectList(typeof(PollType))">
            </select>
            <span asp-validation-for="Type" />
        </div>
        <div class="form-group">
            <label asp-for="Count">Введите количество вопросов</label>
            <input type="text" asp-for="Count" />
            <span asp-validation-for="Count" />
        </div>
        <div class="form-group">
            <input type="submit" value="Далее" class="btn" style="background-color:lightgrey"/>
        </div>
    </div>
</form>

PollApplication/Views/PollCreation/Questions.cshtml
@model List<PollApplication.Models.QuestionModel>

<h1>Вопросы</h1>

@if (@ViewBag.IsIncorrect)
{
    <p>* Некорректные данные.</p>
}
<div id="Questions">
    <form asp-action="Questions" asp-controller="PollCreation" method="post">
        @for (int i = 0; i < @ViewBag.Count; i++)
        {
        <div class="form-group">
            <input type="text" name="[@i].Text" placeholder="Вопрос" value="" />
            <input type="hidden" value="@ViewBag.Type" name="[@i].Type" />
            <input type="hidden" value="@ViewBag.Count" name="[@i].Count" />
            <input type="hidden" value="@ViewBag.Name" name="[@i].Name" />
            <div class="col" id="Variants">
                <div id="variant(@i)-1">
                    <input type="text" name="[@i].Variants[0]" placeholder="Вариант ответа" value="" />
                </div>
                <div id="variant(@i)-2">
                    <input type="text" name="[@i].Variants[1]" placeholder="Вариант ответа" value="" />
                </div>
                <div class="col-5">
                    <input type="button" value="Добавить вариант ответа" onclick="AddVariant(this, @i, 2)" />
                    <input type="button" value="Убрать вариант ответа" onclick="RemoveVariant(this, 1)" />
                </div>
            </div>
        </div>
        }
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn" style="background-color:lightgrey"/>
        </div>
    </form>
</div>

@section Scripts
{
    <script type="text/javascript">
        function AddVariant(button, count, variant) {
            var divOne = $("<div />");
            var divTwo = $("<div />");
            var newButtonAdd = $("<input />").attr("type", "button").attr("value", "Добавить вариант ответа")
                .attr("onclick", "AddVariant(this, " + count + ", " + (variant + 1) + ")");
            var newButtonRemove = $("<input />").attr("type", "button").attr("value", "Убрать вариант ответа")
                .attr("onclick", "RemoveVariant(this, " + count + ", " + (variant + 1) + ")");
            var newVariant = $("<input />").attr("type", "text")
                .attr("id", "variant(" + count + ")-" + (variant + 1))
                .attr("name", "[" + count + "].Variants[" + variant + "]")
                .attr("placeholder", "Вариант ответа");
            divOne.append(newVariant);
            if (variant < 11) {
                divTwo.append(newButtonAdd);
            }
            divTwo.append(newButtonRemove);
            $(button).parent().parent().append(divOne);
            $(button).parent().parent().append(divTwo);
            $(button).parent().remove();
        }

        function RemoveVariant(button, count, variant) {
            if (variant > 2) {
                var div = $("<div />");
                var newButtonAdd = $("<input />").attr("type", "button").attr("value", "Добавить вариант ответа")
                    .attr("onclick", "AddVariant(this, " + count + ", " + variant + ")");
                var newButtonRemove = $("<input />").attr("type", "button").attr("value", "Убрать вариант ответа")
                    .attr("onclick", "RemoveVariant(this, " + count + ", " + (variant - 1) + ")");
                div.append(newButtonAdd);
                div.append(newButtonRemove);
                document.getElementById("variant(" + count + ")-" + variant).remove();
                $(button).parent().parent().append(div);
                $(button).parent().remove();
            }
        }
    </script>
}