PollApplication/Models/Poll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollApplication.Models
{
    public class Poll
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public ICollection<Question> Questions { get; set; }
        public int Count { get; set; }
        public PollType Type { get; set; }

        public Poll()
        {
        }
    }
}

PollApplication/Models/PollViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollApplication.Models
{
    public class PollViewModel
    {
        public string SearchString { get; set; }
        public List<Poll> Polls { get; set; }
    }
}

PollApplication/Models/StatViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollApplication.Models
{
    public class StatViewModel
    {
        public string QuestionText { get; set; }
        public int Id { get; set; }
        public List<SimpleReportViewModel> Models { get; set; }
    }
}

PollApplication/Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PollApplication.Models;

namespace PollApplication.Controllers
{
    public class PollsController : Controller
    {
        private ApplicationContext _context;
        private int userId;
        public PollsController(ApplicationContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var email = httpContextAccessor.HttpContext.User.Claims.First(claim => claim.Value.Contains("@")).Value;
            userId = _context.Users.FirstOrDefault((user =>
                user.Email == email)).Id;
        }

        public async Task<IActionResult> Index(string searchString, int user)
        {
            userId = user;
            var polls = from p in _context.Polls
                select p;
            polls = polls.OrderByDescending((poll => poll.Date));

            if (!string.IsNullOrEmpty(searchString))
            {
                polls = polls.Where((poll => poll.Name.Contains(searchString)));
            }

            PollViewModel pvm = new PollViewModel()
            {
                Polls = await polls.ToListAsync(),
            };

            return View(pvm);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(string searchString)
        {
            var polls = from p in _context.Polls select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                polls = polls.Where((poll => poll.Name.Contains(searchString)));
            }

            PollViewModel pvm = new PollViewModel()
            {
                Polls = await polls.ToListAsync(),
            };

            return View(pvm);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteById(int id)
        {
            foreach (var q in _context.Questions.Where((question => question.LinkedPollId==id)))
            {
                foreach (var answer in _context.Answers.Where((answer => answer.QuestionId==q.Id)))
                {
                    _context.Answers.Remove(answer);
                }

                foreach (var variant in _context.Variants.Where((varia => varia.QuestionId==q.Id)))
                {
                    _context.Variants.Remove(variant);
                }

                _context.Questions.Remove(q);
            }

            _context.Polls.RemoveRange(await _context.Polls.FirstOrDefaultAsync((poll => poll.Id==id)));
            await _context.SaveChangesAsync();

            return RedirectToAction("Delete");
        }

        public async Task<IActionResult> Pass(int id, bool redirect = false)
        {
            Poll p = await _context.Polls.FirstOrDefaultAsync(poll => poll.Id == id);
            if (p is null)
            {
                return RedirectToAction("Index");
            }

            List<Question> questions = _context.Questions.Where((question => question.LinkedPollId == p.Id)).ToList();
            if (!redirect)
            {
                foreach (var q in questions)
                {
                    var foundAnswer = await _context.Answers.FirstOrDefaultAsync((a =>
                        a.UserId == userId && a.QuestionId == q.Id));
                    if (foundAnswer != null)
                    {
                        ViewBag.UserId = userId;
                        ViewBag.PollId = id;
                        return View("Modal");
                    }
                }
            }

            ViewBag.PollName = p.Name;
            if (p.Type == PollType.Check)
            {
                return PassCheck(questions);
            }

            return PassRadio(questions);
        }

        public async Task<IActionResult> Stat(int id)
        {
            Poll p = await _context.Polls.FirstOrDefaultAsync(poll => poll.Id == id);
            if (p is null)
            {
                return RedirectToAction("Index");
            }

            List<Question> questions = await _context.Questions.Where((question => question.LinkedPollId == p.Id)).ToListAsync();
            List<StatViewModel> statView = new List<StatViewModel>();
            int counter = 1;
            foreach (var q in questions)
            {
                List<SimpleReportViewModel> answers = new List<SimpleReportViewModel>();
                foreach (var variant in _context.Variants.Where((variant => variant.QuestionId==q.Id)))
                {
                    SimpleReportViewModel report = new SimpleReportViewModel()
                    {
                        DimensionOne = variant.Text,
                        Quantity = await _context.Answers.Where((answer => answer.VariantId==variant.Id)).CountAsync()
                    };

                    answers.Add(report);
                }

                statView.Add(new StatViewModel(){Models = answers, QuestionText = "Вопрос "+counter+". "+q.QuestionText, Id = counter});
                counter++;
            }

            return View(statView);
        }

        public IActionResult PassRadio(List<Question> questions)
        {
            List<QuestionRadioViewModel> viewList = new List<QuestionRadioViewModel>();
            foreach (Question q in questions)
            {
                QuestionRadioViewModel model = new QuestionRadioViewModel()
                {
                    QuestionId = q.Id,
                    Question = q.QuestionText,
                    Variants = _context.Variants.Where((variant => variant.QuestionId == q.Id))
                        .ToList(),
                };
                viewList.Add(model);
            }


            return View("PassRadio", viewList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PassRadio(List<QuestionRadioViewModel> models)
        {
            if (userId == 1)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                foreach (var model in models)
                {
                    if (model.AnswerId == 0)
                    {
                        ModelState.AddModelError("", "Некорректные ответы");
                        return View(models);
                    }

                    var foundAnswer = await _context.Answers.FirstOrDefaultAsync((a =>
                        a.UserId == userId && a.QuestionId == model.QuestionId));
                    if (foundAnswer != null)
                    {
                        _context.Answers.Remove(foundAnswer);
                    }

                    PollAnswer answer = new PollAnswer()
                    {
                        UserId = userId, QuestionId = model.QuestionId, VariantId = model.AnswerId
                    };

                    _context.Answers.Add(answer);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Некорректные ответы");
            return View(models);
        }

        public IActionResult PassCheck(List<Question> questions)
        {
            List<QuestionCheckViewModel> viewList = new List<QuestionCheckViewModel>();
            foreach (Question q in questions)
            {
                QuestionCheckViewModel model = new QuestionCheckViewModel()
                {
                    QuestionId = q.Id,
                    Question = q.QuestionText,
                    Variants = _context.Variants.Where((variant => variant.QuestionId == q.Id))
                        .ToList(),
                };
                viewList.Add(model);
            }

            return View("PassCheck", viewList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PassCheck(List<QuestionCheckViewModel> models)
        {
            if (userId == 1)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                foreach (var model in models)
                {
                    if (model.Answers.Count==0)
                    {
                        ModelState.AddModelError("", "Некорректные ответы");
                        return View(models);
                    }

                    var foundAnswers = _context.Answers.Where((a =>
                        a.UserId == userId && a.QuestionId == model.QuestionId));
                    if (foundAnswers.Count() != 0)
                    {
                        foreach (var answerFound in foundAnswers)
                        {
                            _context.Answers.Remove(answerFound);
                        }
                    }

                    for (int i = 0; i < model.Answers.Count; i++)
                    {
                        PollAnswer answer = new PollAnswer()
                        {
                            UserId = userId,
                            QuestionId = model.QuestionId,
                            VariantId = model.Variants[model.Answers[i]].Id
                        };

                        _context.Answers.Add(answer);
                        await _context.SaveChangesAsync();
                    }
                }

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Некорректные ответы");
            return View(models);
        }
    }
}

PollApplication/Views/Polls/Delete.cshtml
@model PollApplication.Models.PollViewModel

<h1>Опросы</h1>

<form asp-action="Index" method="get">
    <p>
        Название: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Найти" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Количество вопросов
            </th>
            <th>
                Дата
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Polls)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-action="Pass" asp-route-id="@item.Id">Демо-опрос</a>
            </td>
            <td>
                <a asp-action="DeleteById" asp-route-id="@item.Id">Удалить опрос</a>
            </td>
        </tr>
        }
    </tbody>
</table>

PollApplication/Views/Polls/Index.cshtml
@model PollApplication.Models.PollViewModel

<h1>Опросы</h1>

<form asp-action="Index" method="get">
    <p>
        Название: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Найти" />
    </p>
</form>

<table class="table">
    <thead>
    <tr align="center">
        <th align="center">
            Название
        </th>
        <th align="center">
            Количество вопросов
        </th>
        <th align="center">
            Дата
        </th>
        <th align="center"></th>
        <th align="center"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Polls)
    {
        <tr align="center">
            <td align="center">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        <td align="center">
            <a asp-action="Pass" asp-route-id="@item.Id">Пройти опрос</a>
        </td>
        <td align="center">
            <a asp-action="Stat" asp-route-id="@item.Id">Статистика</a>
        </td>
        </tr>
    }
    </tbody>
</table>

PollApplication/Views/Polls/Modal.cshtml
<h3>Вы уже проходили этот тест, желаете перепройти?</h3>
<br/>
<p><a class="btn btn-info" asp-action="Pass" asp-route-id="@ViewBag.PollId" asp-route-redirect="true">Да&#160;</a></p>
<p><a class="btn btn-info" asp-action="Index" asp-route-user="@ViewBag.UserId">Нет</a></p>

PollApplication/Views/Polls/PassCheck.cshtml
@model List<QuestionCheckViewModel>

<div class="validation" asp-validation-summary="ModelOnly"></div>
<form asp-action="PassCheck" asp-controller="Polls">
    <h3 align="center">@ViewBag.PollName (@Model.Count вопросов)</h3>
    @for (int k = 0; k < Model.Count; k++)
    {
        <h4>@(k + 1). @Model[k].Question</h4>
        <input type="hidden" value="@Model[k].Question" name="[@k].Question" />
        <input type="hidden" value="@Model[k].QuestionId" name="[@k].QuestionId" />
        <div class="form-group">
            @for (int i = 0; i < Model[k].Variants.Count; i++)
            {
                <p><input type="checkbox" name="[@k].Answers" value="@i"> @Html.DisplayFor((model => Model[k].Variants[i].Text))</p>
                <input type="hidden" value="@Model[k].Variants[i].Text" name="[@k].Variants[@i].Text" />
                <input type="hidden" value="@Model[k].Variants[i].Id" name="[@k].Variants[@i].Id" />
            }
        </div>
    }
    <div class="form-group">
        <input type="submit" value="Далее" class="btn" style="background-color: lightgrey" />
    </div>
</form>

PollApplication/Views/Polls/PassRadio.cshtml
@model List<QuestionRadioViewModel>

    <div class="validation" asp-validation-summary="ModelOnly"></div>
<form asp-action="PassRadio" asp-controller="Polls">
    <h3 align="center">@ViewBag.PollName (@Model.Count вопросов)</h3>
    @for (int k = 0; k < Model.Count; k++)
    {
        <h4>@(k + 1). @Model[k].Question</h4>
        <input type="hidden" value="@Model[k].Question" name="[@k].Question"/>
        <input type="hidden" value="@Model[k].QuestionId" name="[@k].QuestionId"/>
        <div class="form-group">
            @for (int i = 0; i < Model[k].Variants.Count; i++)
            {
                <p>@Html.RadioButtonFor((model => model[@k].AnswerId), Model[@k].Variants[i].Id) @Html.DisplayFor((model => Model[k].Variants[i].Text))</p>
                <input type="hidden" value="@Model[k].Variants[i].Text" name="[@k].Variants[@i].Text"/>
                <input type="hidden" value="@Model[k].Variants[i].Id" name="[@k].Variants[@i].Id"/>
            }
        </div>
    }
    <div class="form-group">
        <input type="submit" value="Далее" class="btn" style="background-color: lightgrey"/>
    </div>
</form>

PollApplication/Views/Polls/QuestionPieChart.cshtml
@using System.Linq;
@model StatViewModel
@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Models.Select(x => x.DimensionOne).ToList());
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Models.Select(x => x.Quantity).ToList());
    var i = Model.Id;
    ViewData["Title"] = "Pie Chart";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pie</title>
</head>
<body>
    <div class="box-body">

        <div class="chart-container">
            <canvas id="chart-@i" style="width:100%; height:500px"></canvas>
        </div>
    </div>
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type="text/javascript">

        $(function () {
    var chartName = "chart-@i";
        var ctx = document.getElementById(chartName).getContext('2d');
        var data = {
                labels: @Html.Raw(XLabels),
                datasets: [{
                    label: "Drinks Chart",
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 0, 0)',
                        'rgba(0, 255, 0)',
                        'rgba(0, 0, 255)',
                        'rgba(192, 192, 192)',
                        'rgba(255, 255, 0)',
                        'rgba(255, 0, 255)'
                    ],
                    borderWidth: 1,
                    data: @Html.Raw(YValues)
    }]
            };

var options = {
                maintainAspectRatio: false,
};

       var myChart = new  Chart(ctx, {
                options: options,
                data: data,
                type:'pie'

            });
        });
</script>  

PollApplication/Views/Polls/Stat.cshtml
@model List<StatViewModel>

@foreach (var statView in Model)
{
    <h3 align="center">@statView.QuestionText</h3>
    <p>
        @{ Html.RenderPartial("QuestionPieChart", statView);}
    </p>
}